(deftheme MightyDark
  "Created 2017-03-13.")

(custom-theme-set-faces
 'MightyDark
 '(default ((t (:inherit nil :stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Menlo"))))
 '(cursor ((((background light)) (:background "black")) (((background dark)) (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#d55e00"))))
 '(minibuffer-prompt ((t (:weight bold :box (:line-width -1 :color "red" :style released-button) :foreground "#0072b2" :background "yellow"))))
 '(highlight ((t (:underline (:color foreground-color :style line) :foreground "#0072b2" :background "#e5e5e5"))))
 '(region ((t (:background "#f8ec59"))))
 '(shadow ((t (:foreground "grey70"))))
 '(secondary-selection ((t (:weight bold :foreground "#f6f3e8" :background "#e5e5e5"))))
 '(trailing-whitespace ((t (:background "#d55e00"))))
 '(font-lock-builtin-face ((t (:foreground "#0072b2"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "Salmon"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#009e73"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "#d55e00"))))
 '(font-lock-doc-face ((t (:slant oblique :foreground "indian red"))))
 '(font-lock-function-name-face ((t (:height 1.1 :weight bold :foreground "#d55e00"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#56b4e9"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:slant italic :foreground "cornflower blue"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :inherit nil))))
 '(font-lock-string-face ((t (:foreground "#848ea9"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#0072b2"))))
 '(font-lock-variable-name-face ((t (:weight bold :foreground "#e69f00"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "hot pink"))))
 '(button ((t (:weight bold :underline (:color foreground-color :style line) :box (:line-width 2 :color "grey" :style released-button) :foreground "black" :background "grey"))))
 '(link ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#0072b2"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#cc79a7"))))
 '(fringe ((t (:foreground "Wheat" :background "#f7f7f7"))))
 '(header-line ((t (:height 0.9 :weight bold :underline (:color "black" :style line) :overline "black" :box (:line-width -1 :color "red" :style released-button) :inverse-video t :foreground "grey90" :background "grey20"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow"))))
 '(mode-line ((t (:family "DejaVu Sans" :height 0.9 :box (:line-width -1 :color nil :style released-button) :foreground "black" :background "#e5e5e5"))))
 '(mode-line-buffer-id ((t (:height 0.9 :weight bold :foreground "red" :background "grey65"))))
 '(mode-line-emphasis ((t (:weight bold :foreground "white"))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button) :foreground "yellow"))))
 '(mode-line-inactive ((t (:height 0.9 :weight light :box (:line-width -1 :color nil :style released-button) :foreground "black" :background "#b0b0b0" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :underline (:color "#FF9632" :style line) :foreground "white" :background "#d55e00"))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "red4"))))
 '(lazy-highlight ((t (:underline (:color "#FF9632" :style line) :foreground "white" :background "#cc79a7"))))
 '(match ((t (:weight bold :background "RoyalBlue3"))))
 '(next-error ((t (:underline nil :background "blue3"))))
 '(query-replace ((t (:foreground "brown4" :background "palevioletred2")))))

(provide-theme 'MightyDark)
